### ISSUE TITLE
Concave hulls

### ISSUE THREAD

**Issue by mpadge** [ropensci/mapscanner#1]
Convex hulls currently implemented, but can be switched to concave via [concaveman C++ code](https://github.com/sadaszewski/concaveman-cpp) once [this issue](https://github.com/sadaszewski/concaveman-cpp/issues/3) has been resolved. That code can then be bundled here to generate the hulls.

Ping @mdsumner - check out the link - concaveman in C++, so no otherwise game-killer `V8` dep for the `.js` version. It's got a :bug: that need a-fixin; once that's done, we can bundle and use it as we like ... happy days

**Comment by mdsumner** [comment]
sheesh you on 🔥

**Comment by mpadge** [comment]
Ah shite, it doesn't work! The V8 port works on these data, but the C++ version gives this:
![junk](https://user-images.githubusercontent.com/6697851/60880971-09100a00-a245-11e9-8d1f-fecd629e95a7.png)

It's not quite production ready, so I'll put all this over in a `concaveman` branch and ditch it from main until a fix can be found.

**Comment by mdsumner** [comment]
sufferin' succotash!!

**Comment by mpadge** [comment]
Opened issue at [concaveman-cpp](https://github.com/sadaszewski/concaveman-cpp/issues/5), so we'll see what happens ...

**Comment by mpadge** [comment]
@mdsumner it all works, and that commit bundles it. Sweeet!!!! :lollipop:
