### ISSUE TITLE
map style parameter

### ISSUE THREAD

**Issue by mpadge** [ropensci/mapscanner#10]
Currently hard-coded to `mapbox-light`. Open it up to [all styles](https://docs.mapbox.com/studio-manual/overview/map-styling/#template-styles)

**Comment by mpadge** [comment]
Re-opened until the three available styles have been documented

**Comment by mpadge** [comment]
@mdsumner Just in case you've got any suggestions here. I have now enable three mapbox `styles` for the maps, and documented those in a separate vignette, but I can't put it in the package because it bloats it out to 6.4MB installed size. The current vignette alone is 3.8MB; the proposed new one with three additional images another 1.8, for total 5.6MB in `inst/doc`, which is a no-go. I don't see any way of reducing size of current vignette, when most of the size is taken by the `ggplot` outputs of polygon overlays. This proposed new one was intended merely to demonstrate the three available styles, because these are not readily viewable via mapbox.

Current options appear to be:

1. Include the new vignette and explain to CRAN the unavoidability of large package because it's about maps and we need to include map images to demonstrate;
2. Forget about this, and just get users to click mapbox link now given in [`ms_generate_map()` function](https://mpadge.github.io/mapscanner/reference/ms_generate_map.html) to get a bit of an idea of styles
3. Find a way to reduce package size ... but I really don't think that is possible any further. I've squeezed everything i can out of bundled image files, and as said, it's the dynamically generated `ggplot2` images that are now the killer.

Thoughts appreciated!

**Comment by mdsumner** [comment]
I'll check, maybe the webshot pngs are more bigger than needed?  Maybe post process to reduce colours (or use JPEG, blasphemy I know ...)

**Comment by mpadge** [comment]
I've gotten rid of almost all colours, and they're not webshot pngs; they're just the ones produced by the package then `magick`ed down to 30% size. Any smaller and you can hardly see a thing, and that puts the actual maps at around 100k, which is fine.

**Comment by mdsumner** [comment]
That's all I would have tried

**Comment by mpadge** [comment]
That commit adds a new vignette to the repo here, but not in the CRAN version (because it bloats to around 7MB).
