### ISSUE TITLE
reduce package imports

### ISSUE THREAD

**Issue by mpadge** [ropensci/mapscanner#11]
It currently has a quite beastly list of `Imports`, many of which should be moved to `Suggests`, including:

- [ ] `jpeg`
- [ ] `sf`
- [ ] `polyclip`

At least `sf` should be `Suggest`ed rather than `Import`ed, to lower the install burden. `polyclip` is only used for a single `pointinpolygon` call in `aggregate_polys`, so this will be able to be removed entirely if #2 results in bundling `clipper` here.

**Comment by mpadge** [comment]
Closing for the moment, to maybe revisit later. The biggest remaining dependency is definitely `sf`, which is really only needed for the final [reprojection steps](https://github.com/mpadge/mapscanner/blob/master/R/rectify-maps.R#L392-L394), but that could be done directly via `reproj` and so allow `sf` to be ditched completely, or at least replaced with `sfheaders`. @mdsumner any thoughts on this? Would `reproj` be up to the task, given that we are actually just dealing with coordinate matrices for all but the final steps which wrap these as `sfc`? The matrices could just be kept, `reproj`-ed, then `sfheaders`-ified into `sfc` -> `sf` objects. All possible, right?

**Comment by mdsumner** [comment]
Definitely. I have a bit of a bumpy update for reproj coming, it will use PROJ preferentially when it can and I have a few deps to check over, but so far so good. I'll have a look at the needs here but it should be simple

**Comment by mpadge** [comment]
cool, great to know. This is not super high priority at the mo, but it'll definitely be good to ditch the `sf` dep at some stage.
