### ISSUE TITLE
envvars or options for mapbox API key?

### ISSUE THREAD

**Issue by mpadge** [ropensci/mapscanner#14]
@symbolixAU, a question for you, if i may. In mapdeck, you use `options` to store and extract the mapbox API key, which requires the user to explicitly `set_token()`. This package of mine uses envvars, which enables direct auto-extraction which [you do anyway](https://github.com/SymbolixAU/mapdeck/blob/master/R/mapdeck_tokens.R#L77-L88) during `set_token()`. Is there then any reason why you use options, rather than direct auto-extraction of envvars? I presume, like your source-files-in-inst approach, that the answer is yes, and would be keen to hear.

Note also that I just use the following
``` r
e <- Sys.getenv()
e <- e [grep ("mapbox|mapscan", names (e), ignore.case = TRUE)]
tok <- unique (as.character (e))
```
And then proceed if there is a single unique non-null token. That might be somewhat simpler than your current code to guess probable token names? It's also slightly more secure because your code could return multiple envvars with different tokens, yet you ultimately presume the first is the right one. My code allows multiple envvars, but proceeds only if there is a single unique token, regardless of how many different variables share that value. (Note also that your current [`if(length(api) == 0)` line](https://github.com/SymbolixAU/mapdeck/blob/master/R/mapdeck_tokens.R#L86) can never be met, because unnaming a non-existent envvar still returns `""`, which has length 1.)

But to return to the real question: Why `options` and not just `Sys.getenv`? (And finally, note that I still allow a non-enduring way to enter/set a key via an *optional* set key fn, but still set as an envvar, because these are destroyed with current R session anyway, so I presume that is safe?)

**Comment by SymbolixAU** [comment]
> Is there then any reason why you use options, rather than direct auto-extraction of envvars?

I can't honestly say why I initially chose options over envars. I **think** it's because our office had a policy of not reading from environment variables so all scripts were reproducible between different computers. However, the latest update which [you point to](https://github.com/SymbolixAU/mapdeck/issues/209) now allows envars too.

I've re-opened my 'get_access_token' issue to consider your points here.

**Comment by dcooley** [comment]
> (Note also that your current if(length(api) == 0) line can never be met, because unnaming a non-existent envvar still returns "", which has length 1.)

is this true? 

```r
e <- Sys.getenv()
e <- e[ grep("mynonexistentenvar", names(e))]

e <- unname( e[which(nzchar(e))] )

length( e )
# 0
```

**Comment by mpadge** [comment]
Ah, no, sorry, I see. Difference is you use the two lines:
``` r
e <- Sys.getenv()
e <- e[ grep("mynonexistentenvar", names(e))]
```
which does indeed produce an empty character string, where i use
``` r
e <- Sys.getenv("mynonexistentenvvar")
```
which produces a zero-length string. One could argue that that is a fundamental inconsistency in the way `Sys.envvar()` works, because it should do what your code does, and not what the more straightforward version of my code does... but nobody ever accused R of being a consistent language. All good :smile:

**Comment by dcooley** [comment]
I have [now changed it to use `grep`](https://github.com/SymbolixAU/mapdeck/commit/cb85aafb7a5f9fcf15b230ccd76e7001ac56ec7f) though

**Comment by mpadge** [comment]
Nice. You've got "firt" instead of "first" but.
