### ISSUE TITLE
reduce package installed size

### ISSUE THREAD

**Issue by mpadge** [ropensci/mapscanner#27]
Currently sometimes exceeds 5MB, as noted by @sckott in [review](https://github.com/ropensci/software-review/issues/330#issuecomment-547041251), but this is due to `ggplot2` graphics in the main vignette:
``` r
du <- function (where) {
    x <- system (paste ("du -sh ", where), intern = TRUE)
    message (paste (x, collapse = "\n"))
}
du ("*") # in package repo
#> 928K inst
#> 500K man
#> 1.4M R # mostly local file histories and stuff
#> 1.5M src # same
#> 268K tests
#> 600K vignettes
setwd ("<path>/<to>/<installed>/<package>")
du ("*")
#> 4.3M inst
#> 500K man
#> 72K  R
#> 56K  src
#> 92K  tests
#> 2.0M vignettes
du ("inst/*")
#> 3.4M inst/doc
#> 900K inst/extdata
#> 4.0K inst/paper.md
du ("inst/doc/*")
#> 3.4M inst/doc/mapscanner.html
#> 8.0K inst/doc/mapscanner.R
#> 24K  inst/doc/mapscanner.Rmd
```

<sup>Created on 2019-10-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

And about half of the installed package size (3.4/7 MB) is the *rendered* version of the vignette. The original (repo) directory is only 600K, 380K of which is `vignettes/omaha-polygons.png`. The `ggplot2` images demonstrating [polygon aggregation](https://github.com/mpadge/mapscanner/blob/master/vignettes/mapscanner.Rmd#L375-L393) inflate the package to this unwieldy size. Fiddling with `fig.width` and `fig.height` options in Rmarkdown chunks does nothing either - the size is inherent in the `.eps` info contained within the image itself. Why so big? And what to do about it? ... resort to base graphics?

**Comment by mdsumner** [comment]
drop the png in as a static bitmap and turn off eval for the ggplot?

**Comment by mpadge** [comment]
oh yeah, that should do it. Thanks :rocket:

**Comment by mpadge** [comment]
@mdsumner this one's for future reference: it actually comes from `mapview::mapshot`, which itself just calls `webshot::webshot` and uses default options which are `vwidth = 922` and `vheight = 744` used to determine sizes of viewport to be captured. That results in really large image sizes. Luckily, @tim-salabim foresaw the need to pass additional parameters through to `webshot`, so `mapshot` allows these to be adjusted/reduced. That solves it. Phew.

**Comment by mpadge** [comment]
Closing now, because they're reduced about as much as can be. Package is still 4.5MB with just the four main map images in the vignette, of which 3.4MB is `inst/`, of which 2.4MB is the main vignette. The 1MB that's not `inst/` is from the 2 images in `man/figures` (mostly the polygon image at 390kB), and from the same image repeated in `vignettes`. The 1MB in `inst` that is not the vignette is also these images copied again in `inst/extdata`. There's really not much that can be done about that, and the only real step to reduce size further would be to make only one of the vignette images actually contain a background map, and all other just containing the various polygon outlines absent background. But that looks really crap compared with the current maps, so happy to roll with things the way they are for the moment.

**Comment by sckott** [comment]
Sounds good, thanks @mpadge !
