### ISSUE TITLE
fix raster projection

### ISSUE THREAD

**Issue by mpadge** [ropensci/mapscanner#33]
```
In showSRID(uprojargs, format = "PROJ", multiline = "NO") :
  Discarded ellps unknown in CRS definition: +proj=merc +lon_0=0 +k=1 +x_0=0 +y_0=0 +R=6378137 +units=m +no_defs
```
caused by https://github.com/ropensci/mapscanner/blob/0ec1e9af9e0942f164b0d872fc39a25733927b1e/R/generate-maps.R#L83

@mdsumner it'd be great if you could have a go at this :wink: - let me know

**Comment by mdsumner** [comment]
This is the first time it occurred to use this particular proj string, but sf won't complain, and you can avoid sp warnings: 

```
epsg3857 <- "+proj=merc +a=6378137 +b=6378137 +lat_ts=0 +lon_0=0 +x_0=0 +y_0=0 +k=1 +units=m +nadgrids=@null +wktext +no_defs"
## complains
##raster::projection (out) <- epsg3857  

out@crs@projargs <- epsg3857     
## or
out@crs <- sp::CRS(epsg3857, doCheckCRSArgs = FALSE)

sf::st_crs(raster::projection(out))

```

so maybe that's enough?

**Comment by mdsumner** [comment]
(I had a look at setting up for PR but it's not going to happen today ... just fyi, I appreciate another look at this I have to deal with it in a number of places)

**Comment by mpadge** [comment]
all cool then, i'll leave it in your hands. Thanks loads!

**Comment by mdsumner** [comment]
FYI and note to self, we should compare carefully with 

https://rgdal.r-forge.r-project.org/articles/CRS_projections_transformations.html#transformation-grid-files

https://github.com/r-spatial/sf/issues/1420  (this one I'm not clear where the problem comes from)

**Comment by mdsumner** [comment]
That sf issue is not related, forget it (the ggmap plots mercator in a lonlat frame).

**Comment by mpadge** [comment]
> FYI and note to self, we should compare carefully with
> 
> https://rgdal.r-forge.r-project.org/articles/CRS_projections_transformations.html#transformation-grid-files

yeah, absolutely. That's a great reference - thanks! We're good to close this issue now, right?

**Comment by mdsumner** [comment]
Yes. I haven't done any checks with transforming coords onto it, but I assume you will do that  routinely
