### ISSUE TITLE
Remove RTriangle dep

### ISSUE THREAD

**Issue by mpadge** [ropensci/mapscanner#39]
@mdsumner [`RTriangle`](https://cran.r-project.org/web/packages/RTriangle/index.html) is only used in these lines:
https://github.com/ropensci/mapscanner/blob/151753707fdc67ba4e0a2dba9fd0dd050617cf9b/R/aggregate_polys.R#L138-L140
It also has a [CC by-NC-SA License](https://creativecommons.org/licenses/by-nc-sa/4.0/) which restricts usage (primarily through demanding that all modifications be acknowledged, and an outright prohibition of all commercial usage) in ways that are not directly reconcilable with GPL-3. Any chance that this dep could be ditched in favour of `decido` or something else?

**Comment by mdsumner** [comment]
hmm,  I forget why I didn't think of the license issue - probably just forgot to go from prototype ... I'll have a look

**Comment by mdsumner** [comment]
actually, no sorry to be vague - the planar-*partitioning* ~decomposition~ is not just a product of triangulation but is an extra feature from RTriangle - the only alternative I know of is `st_intersection` which gives the list of which features were involved 


I don't think this existed when we first did this, and I still don't understand it exactly (the GEOS code is a bit mysterious to me), and sadly it's less robust than RTriangle. 

```R
g <- sf::st_sfc(list(sf::st_point(cbind(0, 0)),
                     sf::st_point(cbind(0, 1)),
                     sf::st_point(cbind(1, 0))))
pts <- sf::st_sf(a = 1:3,  geometry = g)
overlapping_polys <- sf::st_buffer(pts, 0.75)

ints <- sf::st_intersection(overlapping_polys)
plot(ints["n.overlaps"])
> ints$origins
[[1]]
[1] 1

[[2]]
[1] 1 2

[[3]]
[1] 2

[[4]]
[1] 1 3

[[5]]
[1] 1 2 3

[[6]]
[1] 2 3

[[7]]
[1] 3


```


I'll keep looking at the sf approach as a replacment, but the only other option is CGAL (we now have [cgalh](https://github.com/dickoa/cgalh) so that's good progress for a future day)

**Comment by mpadge** [comment]
huh, yeah, i see what you mean, and document it here to show why this can not be used in current form:
``` r
n <- 100
g <- lapply (seq (n), function (i) sf::st_point (cbind (runif (1), runif (1))))
g <- sf::st_sfc (g)
pts <- sf::st_sf(a = seq (n),  geometry = g)
overlapping_polys <- sf::st_buffer(pts, 0.25)

ints <- sf::st_intersection(overlapping_polys)
#> Error in CPL_nary_intersection(x): Evaluation error: TopologyException: side location conflict at 0.53146935203228673 0.13085662010930496.
```

<sup>Created on 2020-06-30 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

It's obviously doing some kind of floating-point equality check, for which  ... i say no more.

**Comment by mpadge** [comment]
@mdsumner Finally trying to return here to get this finally on CRAN. This license issue is a bit stumbling block - any advances in  the realms of triangulation the intervening year+?

**Comment by mpadge** [comment]
reprex to reflect current state of things, which suggests it would be okay to ditch current approach in favour of direct `sf::st_intersection()`:

``` r
library (mapscanner)
set.seed (1)
n <- 10
g <- lapply (seq (n), function (i) sf::st_point (cbind (runif (1), runif (1))))
g <- sf::st_sfc (g)
pts <- sf::st_sf(a = seq (n),  geometry = g)
overlapping_polys <- sf::st_buffer(pts, 0.25)
bench::mark (
    rtri = ms_aggregate_polys (overlapping_polys),
    sf = sf::st_intersection(overlapping_polys),
    check = FALSE)
#> Loading required namespace: gibble
#> Loading required namespace: polyclip
#> Warning: Some expressions had a GC in every iteration; so filtering is disabled.
#> # A tibble: 2 × 6
#>   expression      min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr> <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 rtri        541.9ms  541.9ms      1.85        NA    16.6 
#> 2 sf           24.2ms   26.6ms     36.7         NA     1.93
```

<sup>Created on 2021-11-04 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

@mdsumner Anything argue against straight-up usage of `st_intersection()` here?

**Comment by mdsumner** [comment]
no, there's no other alt atm - good that the geos stuff has gotten more robust

**Comment by mdsumner** [comment]
oh, possibly could wrap Triangle without the RTriangle license, I think that it's just "public domain" so you can effectively put whatever license you like on it, with reference to the original source  afaik - but, just mentioning for completeness ;)
