### ISSUE TITLE
Broken image in pkgdwn homepage

### ISSUE THREAD

**Issue by espinielli** [ropensci/mapscanner#45]
In the [home page of the package](https://docs.ropensci.org/mapscanner/) the image just before the "code of conduct" heading is broken.
![Screenshot_2021-11-23-18-31-24](https://user-images.githubusercontent.com/891692/143075117-58acbd41-8139-4355-9f03-134a4e311ffd.png)

Actually all the images are broken. 
(I signal this hoping it doesn't happen to me only)

**Comment by mpadge** [comment]
Oh thanks @espinielli - you're always on the ball!! I'll fix straight away

**Comment by mpadge** [comment]
@espinielli We;ll have to wait for the rOpenSci doc server to build the page, but hopefully the above commit fixes. Thanks

**Comment by mpadge** [comment]
All good - that was a glitch because image links had leading `./`  - the commit which fixed just changed image paths from `./blah/blah` to `blah/blah`.

@jeroen Would it be possible to ensure the doc server works regardless of path format? Alternatively, @maelle do we need to ensure this is documented in Dev Guide somewhere?

**Comment by jeroen** [comment]
https://github.com/r-lib/pkgdown/issues/133#issuecomment-356772547

**Comment by jeroen** [comment]
The way images get copied and stored is implemented in pkgdown, there isn't much I can change about this in the CI.

But I would have expected pkgdown to validate the images though.

**Comment by mpadge** [comment]
Thanks @jeroen - we'll just make sure we've got a note about this somewhere in Dev Guide then. All good. (I suppose i could even implement a check in `pkgcheck` - @maelle as always feel free to open an issue there, or even write a new check, if you think this is important?)
