### ISSUE TITLE
upcoming PROJ/reproj breaks tests

### ISSUE THREAD

**Issue by mdsumner** [ropensci/mapscanner#49]
I need to release a new combo of reproj/PROJ, and this unfortunately breaks this test: 

```
  1. ├─testthat::expect_silent(s <- slippy_bbox(bb)) at test-generate.R:56:5
  2. │ └─testthat:::quasi_capture(enquo(object), NULL, evaluate_promise)
  3. │   ├─testthat (local) .capture(...)
  4. │   │ ├─withr::with_output_sink(...)
  5. │   │ │ └─base::force(code)
  6. │   │ ├─base::withCallingHandlers(...)
  7. │   │ └─base::withVisible(code)
  8. │   └─rlang::eval_bare(quo_get_expr(.quo), quo_get_env(.quo))
  9. ├─mapscanner:::slippy_bbox(bb)
 10. │ └─cbind(afun(xy[, 1L]), afun(xy[, 2L])) %>% ... at mapscanner/R/generate-maps.R:211:5
 11. ├─reproj::reproj(., target = crs, source = srcproj)
 12. └─reproj:::reproj.matrix(., target = crs, source = srcproj)
 13.   ├─base::cbind(do.call(cbind, out), 0)
 14.   └─base::do.call(cbind, out)


```

 I don't actually see a way around this, so I'll let CRAN know and submit a PR for when they are both updated on CRAN.

**Comment by mdsumner** [comment]
There's a similar break in osmdata.   https://github.com/ropensci/osmdata/issues/340

**Comment by mdsumner** [comment]
it might be ok, reproj has hit CRAN and then I'll see how PROJ is after that, I may have been overthinking this ...

**Comment by mpadge** [comment]
I could also just skip those tests on CRAN and resubmit this package prior to your updates? Let me know if that would help ...

**Comment by mdsumner** [comment]
well I think we're ok in the PROJ/reproj sense. Both now updated on CRAN. We'll see how things roll out with the new non-API checks and the testthat/waldo situation. 😱

**Comment by mdsumner** [comment]
ok, was a false alarm it's all fine now. Yay
